# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/mharc/Desktop/small/smallDatabase

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/mharc/Desktop/small/smallDatabase

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/mharc/Desktop/small/smallDatabase/CMakeFiles /mnt/c/Users/mharc/Desktop/small/smallDatabase/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/mharc/Desktop/small/smallDatabase/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named smallDatabase

# Build rule for target.
smallDatabase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smallDatabase
.PHONY : smallDatabase

# fast build rule for target.
smallDatabase/fast:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/build
.PHONY : smallDatabase/fast

Add.o: Add.cpp.o

.PHONY : Add.o

# target to build an object file
Add.cpp.o:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Add.cpp.o
.PHONY : Add.cpp.o

Add.i: Add.cpp.i

.PHONY : Add.i

# target to preprocess a source file
Add.cpp.i:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Add.cpp.i
.PHONY : Add.cpp.i

Add.s: Add.cpp.s

.PHONY : Add.s

# target to generate assembly for a file
Add.cpp.s:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Add.cpp.s
.PHONY : Add.cpp.s

FileOperations.o: FileOperations.cpp.o

.PHONY : FileOperations.o

# target to build an object file
FileOperations.cpp.o:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/FileOperations.cpp.o
.PHONY : FileOperations.cpp.o

FileOperations.i: FileOperations.cpp.i

.PHONY : FileOperations.i

# target to preprocess a source file
FileOperations.cpp.i:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/FileOperations.cpp.i
.PHONY : FileOperations.cpp.i

FileOperations.s: FileOperations.cpp.s

.PHONY : FileOperations.s

# target to generate assembly for a file
FileOperations.cpp.s:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/FileOperations.cpp.s
.PHONY : FileOperations.cpp.s

Menu.o: Menu.cpp.o

.PHONY : Menu.o

# target to build an object file
Menu.cpp.o:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Menu.cpp.o
.PHONY : Menu.cpp.o

Menu.i: Menu.cpp.i

.PHONY : Menu.i

# target to preprocess a source file
Menu.cpp.i:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Menu.cpp.i
.PHONY : Menu.cpp.i

Menu.s: Menu.cpp.s

.PHONY : Menu.s

# target to generate assembly for a file
Menu.cpp.s:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Menu.cpp.s
.PHONY : Menu.cpp.s

Person.o: Person.cpp.o

.PHONY : Person.o

# target to build an object file
Person.cpp.o:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Person.cpp.o
.PHONY : Person.cpp.o

Person.i: Person.cpp.i

.PHONY : Person.i

# target to preprocess a source file
Person.cpp.i:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Person.cpp.i
.PHONY : Person.cpp.i

Person.s: Person.cpp.s

.PHONY : Person.s

# target to generate assembly for a file
Person.cpp.s:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Person.cpp.s
.PHONY : Person.cpp.s

Remove.o: Remove.cpp.o

.PHONY : Remove.o

# target to build an object file
Remove.cpp.o:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Remove.cpp.o
.PHONY : Remove.cpp.o

Remove.i: Remove.cpp.i

.PHONY : Remove.i

# target to preprocess a source file
Remove.cpp.i:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Remove.cpp.i
.PHONY : Remove.cpp.i

Remove.s: Remove.cpp.s

.PHONY : Remove.s

# target to generate assembly for a file
Remove.cpp.s:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Remove.cpp.s
.PHONY : Remove.cpp.s

Search.o: Search.cpp.o

.PHONY : Search.o

# target to build an object file
Search.cpp.o:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Search.cpp.o
.PHONY : Search.cpp.o

Search.i: Search.cpp.i

.PHONY : Search.i

# target to preprocess a source file
Search.cpp.i:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Search.cpp.i
.PHONY : Search.cpp.i

Search.s: Search.cpp.s

.PHONY : Search.s

# target to generate assembly for a file
Search.cpp.s:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Search.cpp.s
.PHONY : Search.cpp.s

Show.o: Show.cpp.o

.PHONY : Show.o

# target to build an object file
Show.cpp.o:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Show.cpp.o
.PHONY : Show.cpp.o

Show.i: Show.cpp.i

.PHONY : Show.i

# target to preprocess a source file
Show.cpp.i:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Show.cpp.i
.PHONY : Show.cpp.i

Show.s: Show.cpp.s

.PHONY : Show.s

# target to generate assembly for a file
Show.cpp.s:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/Show.cpp.s
.PHONY : Show.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/smallDatabase.dir/build.make CMakeFiles/smallDatabase.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... smallDatabase"
	@echo "... edit_cache"
	@echo "... Add.o"
	@echo "... Add.i"
	@echo "... Add.s"
	@echo "... FileOperations.o"
	@echo "... FileOperations.i"
	@echo "... FileOperations.s"
	@echo "... Menu.o"
	@echo "... Menu.i"
	@echo "... Menu.s"
	@echo "... Person.o"
	@echo "... Person.i"
	@echo "... Person.s"
	@echo "... Remove.o"
	@echo "... Remove.i"
	@echo "... Remove.s"
	@echo "... Search.o"
	@echo "... Search.i"
	@echo "... Search.s"
	@echo "... Show.o"
	@echo "... Show.i"
	@echo "... Show.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

